[server]
port = "8081"
host = "localhost"
mode = "debug"

[database]
host = "localhost"
port = 3306
username = "root"
password = "123456"
dbname = "mb_db"
charset = "utf8mb4"
max_idle_conns = 10
max_open_conns = 100
conn_max_lifetime = "1h"

[log]
level = "info"
format = "json"
output = "stdout"
