# 服务器配置
[server]
port = "8090"
host = "localhost"
mode = "debug"  # debug, release, test

# 数据库配置
[database]
host = "localhost"
port = 3306
username = "root"
password = "123456"
dbname = "mb_db"
charset = "utf8mb4"
max_idle_conns = 10
max_open_conns = 100
conn_max_lifetime = "1h"

# Redis配置
[redis]
host = "localhost"
port = 6379
password = ""
db = 0
pool_size = 10

# 日志配置
[log]
level = "info"  # debug, info, warn, error
format = "json"  # json, text
output = "stdout"  # stdout, file

# mysql-agent配置
[agent]
host = "localhost"
port = "8081"
# 可选：base_url = "http://127.0.0.1:8081"
timeout = "120s"
